title: SMAP Today
description: A website for my SMAP Today project. 
theme: just-the-docs

url: https://gillilanda.github.io/smaptoday/

aux_links:
  SMAP Today Repository: https://gillilanda.github.io/smaptoday/
